version: "3.1"
services: 
  nginx-data-flow:
    image: nginx-data-flow
    build: ./nginx
    restart: always
    ports: 
      - 7000:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginxConfig:/etc/nginx/nginxConfig
      - ../web/build:/app
  node-data-flow:
    image: node-data-flow
    build: ./node
    restart: always
    ports: 
      - 7001:7001
    volumes:
      - ../service:/app/egg
